# Generated by Django 3.0.2 on 2021-05-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_ID', models.CharField(max_length=100)),
                ('receiver_ID', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission_Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom_ID', models.CharField(max_length=100)),
                ('sender_ID', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom_ID', models.CharField(max_length=100)),
                ('mission_ID', models.CharField(max_length=100)),
                ('mission_name', models.TextField()),
                ('group_name', models.TextField()),
                ('leader_ID', models.CharField(max_length=100)),
                ('member_ID', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission_imformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_ID', models.CharField(max_length=100)),
                ('mission_name', models.TextField()),
                ('launcher', models.TextField()),
                ('mission_type', models.CharField(max_length=100)),
                ('mission_intro', models.TextField()),
                ('mission_pic', models.TextField()),
                ('joined', models.TextField()),
                ('group_required', models.TextField()),
                ('group_most', models.TextField()),
                ('exp1', models.TextField()),
                ('exp2', models.TextField()),
                ('exp3', models.TextField()),
                ('reward', models.TextField()),
                ('joined_ID', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ID', models.CharField(max_length=100)),
                ('product_name', models.TextField()),
                ('product_detail', models.TextField()),
                ('product_price', models.TextField()),
                ('product_left', models.TextField()),
            ],
        ),
    ]
