# Generated by Django 3.0.2 on 2021-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_friend_chatroom_mission_chatroom_mission_group_mission_imformation_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission_imformation',
            name='group_most',
        ),
        migrations.AddField(
            model_name='mission_group',
            name='group_most',
            field=models.TextField(default=6),
            preserve_default=False,
        ),
    ]
