# Generated by Django 3.0.2 on 2021-05-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210502_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission_group',
            name='status',
            field=models.CharField(default='acceptable', max_length=100),
            preserve_default=False,
        ),
    ]
