# Generated by Django 3.0.2 on 2021-05-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_ID', models.CharField(max_length=100)),
                ('chatroom_ID', models.CharField(max_length=100)),
                ('member_ID', models.TextField()),
                ('submission_pic', models.TextField()),
                ('check_status', models.CharField(max_length=100)),
                ('check_preson', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
