# Generated by Django 3.0.2 on 2021-05-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_mission_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission_submission',
            name='group_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission_submission',
            name='mission_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
