# Generated by Django 3.0.2 on 2021-05-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210504_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_chatroom',
            name='chatroom_ID',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_chatroom_ID',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
