# Generated by Django 3.2 on 2021-05-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210505_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='product_pic',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
