# Generated by Django 3.0.2 on 2021-06-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210524_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shared_chatroom_ID',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
